// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {morpho} from '../models';

export function Analyze(arg1:string):Promise<Array<morpho.Morpheme>>;

export function Train(arg1:string):Promise<void>;
