// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function DeleteWord(arg1) {
  return window['go']['main']['App']['DeleteWord'](arg1);
}

export function GetDictPath() {
  return window['go']['main']['App']['GetDictPath']();
}

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function SaveWord(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWord'](arg1, arg2, arg3);
}

export function SelectDictFile() {
  return window['go']['main']['App']['SelectDictFile']();
}

export function SetDictPath(arg1) {
  return window['go']['main']['App']['SetDictPath'](arg1);
}

export function Train(arg1) {
  return window['go']['main']['App']['Train'](arg1);
}
